import {
  Droplets,
  Pipette,
  Filter,
  Activity,
  Wrench,
  Home,
  Calendar,
  User,
  Wallet,
  Bell,
  Settings,
  LogOut,
  Star,
  Clock,
  MapPin,
  Phone,
  Mail,
  ChevronRight,
  Check,
  X,
  Plus,
  Minus,
  Search,
  Menu,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Database,
  CreditCard,
  FileText,
  MessageSquare,
  AlertCircle,
  CheckCircle,
  XCircle,
  Loader2,
  Users,
  BarChart3,
  TrendingUp,
  IndianRupee,
  CalendarDays,
  ClipboardList,
  UserCog,
  Shield,
  Eye,
  EyeOff,
  MessageCircle,
  ExternalLink,
  Briefcase,
  Target,
  Award,
  Zap,
  Edit,
  Code,
  LogIn,
  UserPlus,
} from "lucide-react"

export const Icons = {
  droplets: Droplets,
  pipette: Pipette,
  filter: Filter,
  activity: Activity,
  wrench: Wrench,
  home: Home,
  calendar: Calendar,
  user: User,
  wallet: Wallet,
  bell: Bell,
  settings: Settings,
  logout: LogOut,
  star: Star,
  clock: Clock,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  chevronRight: ChevronRight,
  check: Check,
  x: X,
  plus: Plus,
  minus: Minus,
  search: Search,
  menu: Menu,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  creditCard: CreditCard,
  fileText: FileText,
  messageSquare: MessageSquare,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  loader: Loader2,
  users: Users,
  barChart: BarChart3,
  trending: TrendingUp,
  rupee: IndianRupee,
  calendarDays: CalendarDays,
  clipboardList: ClipboardList,
  userCog: UserCog,
  shield: Shield,
  eye: Eye,
  eyeOff: EyeOff,
  whatsapp: MessageCircle,
  externalLink: ExternalLink,
  briefcase: Briefcase,
  target: Target,
  award: Award,
  zap: Zap,
  edit: Edit,
  code: Code,
  login: LogIn,
  userPlus: UserPlus,
  database: Database,
}

export function getServiceIcon(iconName: string) {
  const iconMap: Record<string, typeof Droplets> = {
    droplets: Droplets,
    pipette: Pipette,
    filter: Filter,
    activity: Activity,
    wrench: Wrench,
    home: Home,
    calendar: Calendar,
    user: User,
    wallet: Wallet,
    bell: Bell,
    settings: Settings,
    logout: LogOut,
    star: Star,
    clock: Clock,
    mapPin: MapPin,
    phone: Phone,
    mail: Mail,
    chevronRight: ChevronRight,
    check: Check,
    x: X,
    plus: Plus,
    minus: Minus,
    search: Search,
    menu: Menu,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    creditCard: CreditCard,
    fileText: FileText,
    messageSquare: MessageSquare,
    alertCircle: AlertCircle,
    checkCircle: CheckCircle,
    xCircle: XCircle,
    loader: Loader2,
    users: Users,
    barChart: BarChart3,
    trending: TrendingUp,
    rupee: IndianRupee,
    calendarDays: CalendarDays,
    clipboardList: ClipboardList,
    userCog: UserCog,
    shield: Shield,
    eye: Eye,
    eyeOff: EyeOff,
    whatsapp: MessageCircle,
    externalLink: ExternalLink,
    briefcase: Briefcase,
    target: Target,
    award: Award,
    zap: Zap,
    edit: Edit,
    code: Code,
    login: LogIn,
    userPlus: UserPlus,
    database: Database,
  }
  return iconMap[iconName] || Droplets
}
